movies/urls.py
import django


from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('movies/', views.movies, name='movies'),
    path('edit_movie/<int:id>', views.edit_movie, name='edit_movie'),
    path('delete_movie/<int:id>', views.delete_movie, name='delete_movie'),
    path('genres/', views.genres, name='genres'),
    path('edit_genre/<int:id>', views.edit_genre, name='edit_genre'),
    path('delete_genres/<int:id>', views.delete_genre, name='delete_genre'),
    path('liked/<int:id>', views.liked, name='liked'),
    path('filter/<int:genre>', views.filter, name="filter")


]

vidly/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns
from movies import views
from . import views as v
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', v.home, name='home'),
    path('movies/', include('movies.urls')),
    path('genreapi/', views.GenreList.as_view()),
    path('movieapi/', views.MovieList.as_view()),
    path('accounts/', include('accounts.urls')),

]

movies/models.py
from django.db import models
from django.db.models.base import Model
from django.db.models.fields import CharField
from django.utils import timezone
# Create your models here.


class Genre(models.Model):
    name = CharField(max_length=255)

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=255)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    number_in_stock = models.IntegerField()
    daily_rental_rate = models.FloatField()
    date_released = models.IntegerField()
    date_created = models.DateTimeField(default=timezone.now)
    liked = models.BooleanField(default=False)

movies/views.py
import re
from django.core import paginator
from django.http.response import HttpResponseRedirect
from django.shortcuts import redirect, render, get_object_or_404, resolve_url
from django.http import HttpResponse
from django.contrib import messages
from django.core.paginator import Paginator
from .models import Genre, Movie

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import serializers, status
from .serializers import GenreSerializer, MovieSerializer

from django.contrib.auth.decorators import login_required
# Create your views here.

# General Movies Page


@login_required(login_url='accounts:login')
def index(request):
    movie_fields = Movie._meta.fields
    genres = Genre.objects.all().order_by('name')

    if request.method == 'POST':
        column_name = request.POST['column_name']
        order = request.POST.get('order')
        if order == 'ASC':
            movies = Movie.objects.all().order_by(column_name)
        elif order == 'DESC':
            movies = Movie.objects.all().order_by('-'+column_name)

    else:
        movies = Movie.objects.all().order_by('title')
    count = movies.count()
    if count > 0:
        messages.success(request, f'There are {count} movies in the database')

    context = {
        'movies': movies,
        'movie_fields': movie_fields,
        'genres': genres

    }
    return render(request, 'movies/index.html', context)


@login_required(login_url='accounts:login')
def liked(request, id):
    movie = Movie.objects.get(pk=id)
    if movie.liked == True:
        movie.liked = False
    else:
        movie.liked = True
    movie.save()
    return redirect('/movies/')


@login_required(login_url='accounts:login')
def filter(request, genre):
    movie_fields = Movie._meta.fields
    if Movie.objects.filter(genre=genre).exists():
        if genre == '0':
            movies = Movie.objects.all().order_by('title')
        else:
            movies = Movie.objects.filter(genre=genre)
    else:
        movies = Movie.objects.all().order_by('title')
        if genre != 0:
            messages.success(request, 'No records found for this filter')

    genres = Genre.objects.all().order_by('name')
    context = {
        'movies': movies,
        'genres': genres,
        'movie_fields': movie_fields
    }
    return render(request, 'movies/index.html', context)
# Movies Functions


@login_required(login_url='accounts:login')
def movies(request):
    # return HttpResponse("Movies Management Page")
    if request.method == 'POST':
        title = request.POST.get('title')
        genre_id = request.POST.get('genre')
        stock = request.POST.get('stock')
        rate = request.POST.get('rate')
        year = request.POST.get('year')

        if Movie.objects.filter(title=title).exists():
            messages.success(request, 'Movie Exists!')
        else:
            genre = Genre.objects.get(id=genre_id)
            Movie.objects.create(
                title=title,
                genre=genre,
                number_in_stock=stock,
                daily_rental_rate=rate,
                date_released=year
            )
            messages.success(request, 'Movie Added!')
        return redirect('/movies/movies')
    else:
        movies = Movie.objects.all().order_by('title')
        count = movies.count()
        genres = Genre.objects.all().order_by('name')
        paginator = Paginator(movies, per_page=5)
        page_number = request.GET.get('page', 1)
        page_obj = paginator.get_page(page_number)

        if count > 0:
            messages.success(
                request, f'There are {count} movies in the database')

        context = {'genres': genres, 'movies': page_obj.object_list,
                   'page_number': int(page_number), 'paginator': paginator}
        return render(request, 'movies/movies.html', context)


@login_required(login_url='accounts:login')
def edit_movie(request, id):
    if request.method == 'POST':
        title = request.POST.get('title')
        genre_id = request.POST.get('genre')
        stock = request.POST.get('stock')
        rate = request.POST.get('rate')
        year = request.POST.get('year')

        if Movie.objects.filter(title=title).exists():
            messages.success(request, 'Movie Exists!')
            return redirect(f'/movies/edit_movie/{id}')
        else:
            movie = Movie.objects.get(pk=id)
            genre = Genre.objects.get(id=genre_id)
            movie.title = title
            movie.genre = genre
            movie.number_in_stock = stock
            movie.daily_rental_rate = rate
            movie.date_released = year
            movie.save()
            messages.success(request, 'Movie Updated!')
        return redirect('/movies/movies')
    else:
        movie = get_object_or_404(Movie, pk=id)
        genres = Genre.objects.all().order_by('name')
        context = {'movie': movie, 'genres': genres}
        return render(request, 'movies/edit_movie.html', context)


@login_required(login_url='accounts:login')
def delete_movie(request, id):
    if request.method == 'POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        messages.success(request, 'Movie Deleted!')
        return redirect('/movies/movies')
    else:
        movie = Movie.objects.get(id=id)
        context = {'movie': movie}
        return render(request, 'movies/delete_movie.html', context)

# Movie API


class MovieList(APIView):
    def get(self, request):
        movie_query = Movie.objects.all().order_by('title')
        serializer = MovieSerializer(movie_query, many=True)
        return Response(serializer.data)


# Genre Functions

@login_required(login_url='accounts:login')
def genres(request):
    # return HttpResponse("Genre Mangement Page")
    if request.method == 'POST':
        name = request.POST.get('name')
        if Genre.objects.filter(name=name).exists():
            messages.success(request, 'Genre already exists')
        else:
            Genre.objects.create(
                name=name
            )
            messages.success(request, 'Genre Added!')
        return redirect('/movies/genres')

    else:
        genres = Genre.objects.all().order_by('name')
        count = genres.count()
        paginator = Paginator(genres, per_page=5)
        page_number = request.GET.get('page', 1)
        page_obj = paginator.get_page(page_number)

        if count > 0:
            messages.success(
                request, f'There are {count} genres in the database')

        context = {'genres': page_obj.object_list, 'paginator': paginator,
                   'page_number': int(page_number)}
        return render(request, 'movies/genres.html', context)


@login_required(login_url='accounts:login')
def edit_genre(request, id):
    if request.method == 'POST':
        name = request.POST.get('name')
        if Genre.objects.filter(name=name).exists():
            messages.success(request, 'Genre Exists!')
            return redirect(f'/movies/edit_genre/{id}')
        else:
            genre = get_object_or_404(Genre, id=id)
            genre.name = request.POST.get('name')
            genre.save()
            messages.add_message(request, messages.SUCCESS, 'Genre Updated!')
            return redirect('/movies/genres')
    else:
        genre = get_object_or_404(Genre, id=id)
        context = {'genre': genre}
        return render(request, 'movies/edit_genre.html', context)


@login_required(login_url='accounts:login')
def delete_genre(request, id):
    if request.method == 'POST':
        genre = get_object_or_404(Genre, id=id)
        genre.delete()
        messages.success(request, 'Genre Deleted!')
        return redirect('/movies/genres')
    else:
        genre = get_object_or_404(Genre, id=id)
        context = {'genre': genre}
        return render(request, 'movies/delete_genre.html', context)

# Genre API


class GenreList(APIView):
    def get(self, request):
        genre_query = Genre.objects.all().order_by('name')
        serializer = GenreSerializer(genre_query, many=True)
        return Response(serializer.data)

movies/templates/movies/delete_genre.html
{% extends 'base.html' %} {% block content%}
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6 bg-light p-3">
    <h2>{{ genre.name }} Genre</h2>
    <p">Are you sure you want to delete this genre?</p>
    <form method="POST">
      {% csrf_token %}
    
        <input
          type="hidden"
          name="name"
          id="name"
          class="form-control"
          required
          value="{{ genre.id }}"
        />
     

      <div class="form-group mt-2">
        <button
          type="submit"
          class="btn btn-danger"
          name="submit"
          id="submit"
        >
          Delete Genre
        </button>


        <a href="{% url 'movies:genres' %}" class="btn btn-secondary">No, don't delete</a>
      </div>
    </form>
  </div>
  <div class="col-md-3"></div>
</div>

{% endblock %}

movies/templates/movies/delete_movie.html
{% extends 'base.html' %} {% block content%}
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6 bg-light p-3">
    <h2>{{ movie.title }}</h2>
    <p">Are you sure you want to delete this movie?</p>
    <form method="POST">
      {% csrf_token %}
    
        <input
          type="hidden"
          name="name"
          id="name"
          class="form-control"
          required
          value="{{ movie.id }}"
        />
     

      <div class="form-group mt-2">
        <button
          type="submit"
          class="btn btn-danger"
          name="submit"
          id="submit"
        >
          Delete Movie
        </button>


        <a href="{% url 'movies:movies' %}" class="btn btn-secondary">No, don't delete</a>
      </div>
    </form>
  </div>
  <div class="col-md-3"></div>
</div>

{% endblock %}

movies/templates/movies/edit_genre.html
{% extends 'base.html' %} {% block content%}
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6 bg-light p-3">
    <h4 class="text-center">Edit genre form</h4>
    <form method="POST">
      {% csrf_token %}
      <div class="form-group">
        <label for="name">Name</label>
        <input
          type="text"
          name="name"
          id="name"
          placeholder="Enter genre name..."
          class="form-control"
          required
          value="{{ genre.name }}"
        />
      </div>

      <div class="form-group mt-2">
        <button type="submit" class="btn btn-primary" name="submit" id="submit">
          Edit Genre
        </button>

        <a href="{% url 'movies:genres' %}" class="btn btn-secondary"
          >No, don't edit</a
        >
      </div>
    </form>
    {% for m in messages %} {{ m }} {% endfor %}
  </div>
  <div class="col-md-3"></div>
</div>

{% endblock %}

movies/templates/movies/edit_movie.html
{% extends 'base.html' %} {% block content%}
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6 bg-light p-3">
    <h4 class="text-center">Edit movie form</h4>
    <form method="POST">
      {% csrf_token %}
      <div class="form-group">
        <label for="title">Title</label>
        <input
          type="text"
          name="title"
          id="title"
          placeholder="Enter movie title..."
          class="form-control"
          required
          value="{{ movie.title }}"
        />
      </div>
      <div class="form-group">
        <label for="genre">Genre</label>
        <select name="genre" id="genre" class="form-control" required>
          <option value="{{ movie.genre.id}}" selected>{{movie.genre}}</option>
          {% for genre in genres %}
          <option value="{{genre.id}}">{{genre.name}}</option>
          {% endfor %}
        </select>
      </div>
      <div class="form-group">
        <label for="stock">Number In Stock</label>
        <input
          type="number"
          name="stock"
          id="stock"
          placeholder="Enter movie number in stock..."
          class="form-control"
          required
          value="{{ movie.number_in_stock }}"
        />
      </div>
      <div class="form-group">
        <label for="rate">Daily Rental Rate</label>
        <input
          type="text"
          name="rate"
          id="rate"
          placeholder="Enter movie daily rental rate..."
          class="form-control"
          required
          value="{{ movie.daily_rental_rate }}"
        />
      </div>
      <div class="form-group">
        <label for="year">Date Released</label>
        <input
          type="number"
          name="year"
          id="year"
          placeholder="Enter movie release year..."
          class="form-control"
          required
          value="{{ movie.date_released }}"
        />
      </div>
      <div class="form-group mt-2">
        <button type="submit" class="btn btn-primary" name="submit" id="submit">
          Edit Movie
        </button>
        <a href="{% url 'movies:movies' %}" class="btn btn-secondary"
          >No, don't edit</a
        >
      </div>
    </form>
    {% for m in messages %} {{ m }} {% endfor %}
  </div>
  <div class="col-md-3"></div>
</div>

{% endblock %}

movies/templates/movies/genres.html
{% extends 'base.html' %} {% block content%}
<div class="row">
  <div class="col-md-3">
    <h4 class="text-center">Add genre form</h4>
    <form method="POST">
      {% csrf_token %}
      <div class="form-group">
        <label for="name">Name</label>
        <input
          type="text"
          name="name"
          id="name"
          placeholder="Enter genre name..."
          class="form-control"
          required
        />
      </div>

      <div class="form-group mt-2">
        <button
          type="submit"
          class="btn btn-primary w-100"
          name="submit"
          id="submit"
        >
          Add Genre
        </button>
      </div>
    </form>
  </div>
  <div class="col-md-9">
    <p>{% for m in messages %} {{ m }} {% endfor %}</p>
    <table class="table">
      <thead>
        <tr>
          <!-- <th>S/N</th> -->
          <th>Name</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for genre in genres %}

        <tr>
          <!-- <td>{{ forloop.counter }}</td> -->
          <td>{{genre.name }}</td>
          <td>
            <a
              href="{% url 'movies:edit_genre' genre.id %}"
              class="btn btn-warning"
              >Edit</a
            >
          </td>
          <td>
            <a
              href="{% url 'movies:delete_genre' genre.id %}"
              class="btn btn-danger"
              >Delete</a
            >
          </td>
        </tr>

        {% empty %}
        <p>No genres found in database</p>

        {% endfor%}
      </tbody>
    </table>
    <ul class="pagination">
      {% for i in paginator.page_range %}

      <li class="page-item {% if i == page_number %} active {% endif%}">
        <a href="?page={{ i }}" class="page-link">{{i}}</a>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>

{% endblock %}

movies/templates/movies/index.html
{% extends 'base.html' %} {% block content%}
<div class="row">
  <div class="col-md-3">
    <h5>Filter Movies</h5>
    <div class="list-group">
      <a href="{% url 'movies:filter' 0 %}" class="list-group-item list-group-item-action active"
        >All Genres</a
      >
    </div>
    {% for genre in genres %}
    <div class="list-group">
      <a href="{% url 'movies:filter' genre.id %}" class="list-group-item list-group-item-action">{{genre.name}}</a>
    </div>
    {% endfor %}
    
    <h5 class="mt-4">Sort movies</h5>
    <form method="POST">
      {% csrf_token %}
      <div class="form-group">
        <select name="column_name" id="column_name" class="form-control" required>
          <option value="" selected>-- Sort By --</option>
          {% for field in movie_fields %} {% if field.name != 'id' %}
          <option class="form-control" value="{{field.name}}">
           
            {{field.name}}
            
          </option>
          {% endif %} {% endfor %}
        </select>
      </div>

      <div class="form-group mt-2">
        <select name="order" id="order" class="form-control" required>
          <option value="ASC" selected>-- Order By--</option>
          <option class="form-control" value="ASC">Ascending Order</option>
          <option class="form-control" value="DESC">Descending Order</option>
        </select>
      </div>

      <div class="form-group mt-3">
        <button class="btn btn-primary" type="submit" name="submit">
          Sort
        </button>
      </div>
    </form>
  </div>
  <div class="col-md-9">
   
    <p>{% for message in messages %} {{ message }} {% endfor%}</p>
  
    <table class="table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Genre</th>
          <th>Stock</th>
          <th>Rate</th>
          <th>Date Released</th>
          <th></th>
          
        </tr>
      </thead>
      <tbody>
       {% for movie in movies %}
       <tr>
        <td>{{ movie.title }}</td>
        <td>{{ movie.genre }}</td>
        <td>{{ movie.number_in_stock }}</td>
        <td>{{ movie.daily_rental_rate }}</td>
        <td>{{ movie.date_released }}</td>
        <td>
          {% if movie.liked %}
          <a href="{% url 'movies:liked' movie.id%}">
            <i class="fa fa-heart" style="cursor: pointer;"></i>
          </a>
          {% else %}
          <a href="{% url 'movies:liked' movie.id%}">
            <i class="fa fa-heart-o" style="cursor: pointer;"></i>
          </a>
          {% endif %}
        </td>
      </tr>
       {% endfor %}
      </tbody>
    </table>
  
  </div>
</div>

{% endblock %}

movies/templates/movies/movies.html
{% extends 'base.html' %} {% block content%}
<div class="row">
  <div class="col-md-3">
    <h4 class="text-center">Add movie form</h4>
    <form method="POST">
      {% csrf_token %}
      <div class="form-group">
        <label for="title">Title</label>
        <input
          type="text"
          name="title"
          id="title"
          placeholder="Enter movie title..."
          class="form-control"
          required
        />
      </div>
      <div class="form-group">
        <label for="genre">Genre</label>
        <select name="genre" id="genre" class="form-control" required>
          <option value="" selected>-- Choose Genre --</option>
          {% for genre in genres %}
          <option value="{{genre.id}}">{{genre.name}}</option>
          {% endfor %}
        </select>
      </div>
      <div class="form-group">
        <label for="stock">Number In Stock</label>
        <input
          type="number"
          name="stock"
          id="stock"
          placeholder="Enter movie number in stock..."
          class="form-control"
          required
        />
      </div>
      <div class="form-group">
        <label for="rate">Daily Rental Rate</label>
        <input
          type="text"
          name="rate"
          id="rate"
          placeholder="Enter movie daily rental rate..."
          class="form-control"
          required
        />
      </div>
      <div class="form-group">
        <label for="year">Date Released</label>
        <input
          type="number"
          name="year"
          id="year"
          placeholder="Enter movie release year..."
          class="form-control"
          required
        />
      </div>
      <div class="form-group mt-2">
        <button
          type="submit"
          class="btn btn-primary w-100"
          name="submit"
          id="submit"
        >
          Add Movie
        </button>
      </div>
    </form>
  </div>
  <div class="col-md-9">
    <p>{% for m in messages %} {{ m }} {% endfor %}</p>
    <table class="table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Genre</th>
          <th>Stock</th>
          <th>Rate</th>
          <th>Date Released</th>
          <th>
            <!-- <a href="" class="btn btn-warning">Update Movie</a> -->
          </th>
          <th>
            <!-- <a href="" class="btn btn-danger">Delete Movie</a> -->
          </th>
        </tr>
      </thead>
      <tbody>
        {% for movie in movies %}
        <tr>
          <td>{{ movie.title }}</td>
          <td>{{ movie.genre.name }}</td>
          <td>{{ movie.number_in_stock }}</td>
          <td>{{ movie.daily_rental_rate}}</td>
          <td>{{ movie.date_released }}</td>
          <td>
            <a
              href="{% url 'movies:edit_movie' movie.id %}"
              class="btn btn-warning"
              >Edit</a
            >
          </td>
          <td>
            <a
              href="{% url 'movies:delete_movie' movie.id%}"
              class="btn btn-danger"
              >Delete</a
            >
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    <ul class="pagination">
      {% for i in paginator.page_range %}

      <li class="page-item {% if i == page_number %} active {% endif%}">
        <a href="?page={{i}}" class="page-link">{{i}}</a>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>

{% endblock %}