accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.registerPage, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
]

movies/urls.py
import django


from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('movies/', views.movies, name='movies'),
    path('edit_movie/<int:id>', views.edit_movie, name='edit_movie'),
    path('delete_movie/<int:id>', views.delete_movie, name='delete_movie'),
    path('genres/', views.genres, name='genres'),
    path('edit_genre/<int:id>', views.edit_genre, name='edit_genre'),
    path('delete_genres/<int:id>', views.delete_genre, name='delete_genre'),
    path('liked/<int:id>', views.liked, name='liked'),
    path('filter/<int:genre>', views.filter, name="filter")


]

vidly/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns
from movies import views
from . import views as v
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', v.home, name='home'),
    path('movies/', include('movies.urls')),
    path('genreapi/', views.GenreList.as_view()),
    path('movieapi/', views.MovieList.as_view()),
    path('accounts/', include('accounts.urls')),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vidly</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}" />
    <link
      rel="stylesheet"
      href="{% static 'font-awesome/css/font-awesome.css' %}"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'home' %}"> Vidly</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'movies:index' %}">Home </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'movies:movies' %}">Movies </a>
          </li>
          <li class="nav-item ">
            <a target="_blank" class="nav-link" href="/movieapi/"
              >Movies API
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'movies:genres' %}">Genres </a>
          </li>
          <li class="nav-item ">
            <a target="_blank" class="nav-link" href="/genreapi/"
              >Genres API
            </a>
          </li>
          {% if user.is_authenticated %} 
          <li class="nav-item ">
            <a class="nav-link" href="#"
              >{{ request.user }}
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'accounts:logout' %}"
              >Logout
            </a>
          </li>
          {% else %}
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'accounts:login' %}"
              >Login
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'accounts:register' %}"
              >Register
            </a>
          </li>
          {% endif %}
          
        </ul>
      </div>
    </nav>

    <main class="container mt-3">{% block content %} {% endblock %}</main>
  </body>
</html>

templates/home.html
{% extends 'base.html' %} {% block content %}
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <div class="jumbotron bg-light p-3 mt-3 alert">
      <h1>Nnamdi's Movies App</h1>
      <p>
        This is a <b>Django</b> movies Application with
        <b>CRUD</b> functionalities for both movies and genres. <br />
        Also, include functionalities like;<b>
          pagination, filtering and sorting.</b
        >
        <br />
        Inclusive is a <b>RESTFUL APIs</b> for both movies and genres.
      </p>
      <a href="{% url 'accounts:register' %}" class="btn btn-primary"
        >Get Started</a
      >
      <a href="{% url 'accounts:login' %}" class="btn btn-secondary">Login</a>
    </div>
  </div>
  <div class="col-md-2"></div>
</div>
{% endblock %}